movielist/movieapp1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'movieapp1'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.addmovie, name='addmovie'),
    path('update/<int:movie_id>/', views.update, name='update'),
    path('delete/<int:m_id>/', views.delete, name='delete'),
]

movielist/movielist/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp1.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movielist/movieapp1/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')
    desc = models.TextField()

    def __str__(self):
        return self.name

movielist/movieapp1/forms.py
from django import forms
from . models import movie

class movie_form(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name', 'desc', 'image']

movielist/movieapp1/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import movie_form


# Create your views here.
def index(request):
    obj = movie.objects.all()

    return render(request, 'index.html', {'result': obj})


def details(request, movie_id):
    moviee = movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'result': moviee})


def addmovie(request):
    if request.method == 'POST':
        name = request.POST.get('movie_name')
        image = request.FILES['movie_image']
        desc = request.POST.get('movie_desc')
        Movie = movie(name=name, image=image, desc=desc)
        Movie.save()
        return redirect('/')
    return render(request, 'addmovie.html')

def update(request, movie_id):
    mov = movie.objects.get(id=movie_id)
    form = movie_form(request. POST or None, request.FILES, instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': mov})

def delete(request, m_id):
    if request.method == 'POST':
        mov = movie.objects.get(id=m_id)
        mov.delete()
        return redirect('/')

    return render(request, 'delete.html')

movielist/templates/addmovie.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>add</title>-->
<!--</head>-->
<!--<body>-->
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    <input type="text" name="movie_name" placeholder="movie_name"><br>
    <input type="text" name="movie_image" placeholder="Select image">
    <input type="file" name="movie_image" placeholder="movie_image"><br>
    <input type="text" name="movie_desc" placeholder="movie_description"><br>
    <button type="submit" value="Submit">Submit</button>
</form>
<!--</body>-->
<!--</html>-->
{% endblock %}

movielist/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/movie.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Movie Store
      </a>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

movielist/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h1>Are you want to delete this item</h1>
    <input type="submit">
</form>
{% endblock %}

movielist/templates/details.html
{% extends 'base.html' %}
{% block body %}
<img src="{{result.image.url}}" width="100" height="100">
{{result.name}}<br>
{{result.desc}}<br>
<a href="{% url 'movieapp1:update' result.id %}">Update</a>
<a href="{% url 'movieapp1:delete' result.id %}">delete</a>

{% endblock %}

movielist/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
 <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     {{form.as_p}}
<!--     here not write the fields they are already fetched in the view it just called above-->
     <input type="submit">
 </form>

</body>
</html>

movielist/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'home.css' %}">
<div class="container">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3 custom-margin">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" height="350">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <a href="{% url 'movieapp1:details' i.id %}" class="btn btn-primary">Go in detail</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}